_extends: .github
repository:
  name: dependabot-scaffolder
  description: opinionated scaffolder for enabling dependabot on a project
  homepage: 'https://npm.im/@form8ion/dependabot-scaffolder'
  private: false
